# Generated by Django 4.2.7 on 2025-08-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='uuid',
            new_name='token',
        ),
    ]
