# Generated by Django 4.2.7 on 2025-08-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_uuid_invitation_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='token',
            new_name='uuid',
        ),
    ]
